{{- if not .Values.gcp.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  {{ if .Values.gcp.credentialsKeyfilePath }}
  credentialsKeyfilePath: {{ .Values.gcp.credentialsKeyfilePath | b64enc | quote }}
  {{- end }}
  {{ if .Values.gcp.credentialsKeyfileJson }}
  credentialsKeyfileJson: {{ .Values.gcp.credentialsKeyfileJson | b64enc | quote }}
  {{- end }}
  {{ if .Values.gcp.projectID }}
  projectID: {{ .Values.gcp.projectID | b64enc | quote }}
  {{- end }}
{{- end }}
