{{- if not .Values.gcp.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  credentialsKeyfileJson: ""
{{- end }}
