{{- if not .Values.gcp.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  credentialsKeyfilePath: {{ .Values.gcp.credentialsKeyfilePath | b64enc | quote }}
  credentialsKeyfileJson: {{ .Values.gcp.credentialsKeyfileJson | b64enc | quote }}
  projectID: {{ .Values.gcp.projectID | b64enc | quote }}
{{- end }}
